### ISSUE TITLE
Couldnt get Mesos-Slave running, due to DockerContainerizer error

### ISSUE THREAD

**Issue by ggsonigg** [mesosphere/docker-containers#62] opened 2016-07-05 14:50 UTC
Here is my docker version:
~$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

And here is what I am observing:
~$ docker run --net=host --privileged \
>   -e MESOS_PORT=5051 \
>   -e MESOS_MASTER=zk://$ZK_HOST:2181/mesos \
>   -e MESOS_SWITCH_USER=0 \
>   -e MESOS_LOG_DIR=/var/log/mesos \
>   -e MESOS_WORK_DIR=/var/tmp/mesos \
>   -e MESOS_CONTAINERIZERS=docker,mesos \
>   -v "$(pwd)/log/mesos:/var/log/mesos" \
>   -v "$(pwd)/tmp/mesos:/var/tmp/mesos" \
>   -v /var/run/docker.sock:/var/run/docker.sock \
>   -v /cgroup:/cgroup \
>   -v /sys:/sys \
>   -v /usr/local/bin/docker:/usr/local/bin/docker \
>   -v $(which docker):/bin/docker \
>   mesosphere/mesos-slave:0.28.0-2.0.16.ubuntu1404
I0705 22:48:21.905763     1 logging.cpp:188] INFO level logging started!
I0705 22:48:21.906471     1 main.cpp:223] Build: 2016-03-17 17:45:11 by root
I0705 22:48:21.906512     1 main.cpp:225] Version: 0.28.0
I0705 22:48:21.906522     1 main.cpp:228] Git tag: 0.28.0
I0705 22:48:21.906532     1 main.cpp:232] Git SHA: 961edbd82e691a619a4c171a7aadc9c32957fa73
Failed to create a containerizer: Could not create DockerContainerizer: Failed to create docker: Failed to get docker version: Failed to execute 'docker -H unix:///var/run/docker.sock --version': exited with status 127

Any idea what could be wrong?

**Comment by asridharan** [comment] 2016-07-07 18:40
This seems to be a duplicate of #17 . Have a PR pull/63 (https://github.com/mesosphere/docker-containers/pull/63) to fix this.

**Closed by asridharan** 2016-07-07 18:40 UTC
