### ISSUE TITLE
Missing bind mounts for mesos-slave

### ISSUE THREAD

**Issue by isavcic** [mesosphere/docker-containers#46] opened 2016-04-08 11:14 UTC
If you're using Ubuntu 14.04 and the latest stable docker-engine from apt.dockerproject.org, the following error occurs when using the mesos-slave launch snippet from this repo:

> Failed to create a containerizer: Could not create DockerContainerizer: Failed to create docker: Failed to get docker version: Failed to execute 'docker -H unix:///var/run/docker.sock --version': exited with status 127

It turns out that two library bind mounts are missing from the mesos-slave launch snippet:

```
-v /lib/x86_64-linux-gnu/libsystemd-journal.so.0:/lib/x86_64-linux-gnu/libsystemd-journal.so.0 \
-v /usr/lib/x86_64-linux-gnu/libapparmor.so.1:/usr/lib/x86_64-linux-gnu/libapparmor.so.1
```

**Comment by viniiciusconceicao** [comment] 2016-04-08 18:21
I've tried to add the library binds, but it still doesn't work. This is the log from docker:

> I0408 17:51:40.319296     1 logging.cpp:188] INFO level logging started!
> I0408 17:51:40.319582     1 main.cpp:223] Build: 2016-03-17 17:45:11 by root
> I0408 17:51:40.319646     1 main.cpp:225] Version: 0.28.0
> I0408 17:51:40.319658     1 main.cpp:228] Git tag: 0.28.0
> I0408 17:51:40.319663     1 main.cpp:232] Git SHA: 961edbd82e691a619a4c171a7aadc9c32957fa73
> Failed to create a containerizer: Could not create DockerContainerizer: Failed to create docker: Failed to get docker version: Failed to execute 'docker -H unix:///var/run/docker.sock --version': exited with status 127

**Comment by isavcic** [comment] 2016-04-08 18:58
Good catch. Do you bind mount `/usr/bin/docker` or `/usr/bin/local/docker`? If you're using the official docker-engine package, it's /usr/bin/docker. Can you please verify? Thanks.

**Comment by isavcic** [comment] 2016-04-08 19:04
In more detail, on Ubuntu 14.04, the following should work:
```
docker run -d --net=host --privileged \
  -e MESOS_PORT=5051 \
  -e MESOS_MASTER=zk://127.0.0.1:2181/mesos \
  -e MESOS_SWITCH_USER=0 \
  -e MESOS_CONTAINERIZERS=docker,mesos \
  -e MESOS_LOG_DIR=/var/log/mesos \
  -e MESOS_WORK_DIR=/var/tmp/mesos \
  -v "$(pwd)/log/mesos:/var/log/mesos" \
  -v "$(pwd)/tmp/mesos:/var/tmp/mesos" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /cgroup:/cgroup \
  -v /sys:/sys \
  -v "$(which docker):/usr/local/bin/docker" \
  -v /lib/x86_64-linux-gnu/libsystemd-journal.so.0:/lib/x86_64-linux-gnu/libsystemd-journal.so.0 \
  -v /usr/lib/x86_64-linux-gnu/libapparmor.so.1:/usr/lib/x86_64-linux-gnu/libapparmor.so.1 \
  mesosphere/mesos-slave:0.28.0-2.0.16.ubuntu1404
```

`$(pwd)` included from the original snippet (NB: I prefer to bind mount a specific folder on the system instead of that).

**Comment by viniiciusconceicao** [comment] 2016-04-08 19:10
Thanks @isavcic ! I am using the official one. After removing the local part it works. This is the snippet I used: 

> docker run -d --net=host --privileged \
  -e MESOS_PORT=5051 \
  -e MESOS_MASTER=zk://127.0.0.1:2181/mesos \
  -e MESOS_SWITCH_USER=0 \
  -e MESOS_CONTAINERIZERS=docker,mesos \
  -e MESOS_LOG_DIR=/var/log/mesos \
  -e MESOS_WORK_DIR=/var/tmp/mesos \
  -v "$(pwd)/log/mesos:/var/log/mesos" \
  -v "$(pwd)/tmp/mesos:/var/tmp/mesos" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /cgroup:/cgroup \
  -v /sys:/sys \
  -v /usr/bin/docker:/usr/bin/docker \
  -v /lib/x86_64-linux-gnu/libsystemd-journal.so.0:/lib/x86_64-linux-gnu/libsystemd-journal.so.0 \
  -v /usr/lib/x86_64-linux-gnu/libapparmor.so.1:/usr/lib/x86_64-linux-gnu/libapparmor.so.1 \
  mesosphere/mesos-slave:0.28.0-2.0.16.ubuntu1404

**Comment by PetaPetaPeta** [comment] 2016-05-14 23:27
For the newest you also need the file `/usr/lib/x86_64-linux-gnu/libltdl.so.7`

**Comment by asridharan** [comment] 2016-07-05 17:47
Would it be enough to document the instructions for docker run for launching these Images?

**Comment by asridharan** [comment] 2016-07-07 04:51
This issue is the same problem with #17 . The absence of docker client in the container image seems to be the root cause of these issues. Hence marking it as a duplicate of #17 and closing this. Lets try to figure out if bundling a docker client with the image is an option.

**Closed by asridharan** 2016-07-07 04:51 UTC
Labels: duplicate
